name: Quarkus apps CI

on:
  pull_request:
    paths-ignore:
      - '.github/**'
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'maven'

      - name: Build and test weather-app
        run: |
          cd weather-app
          ./mvnw -B clean package


